### ISSUE TITLE
Not reading new driver files

### ISSUE THREAD

**Issue by ramasofficial** [jugglingcats/tachograph-reader#55] opened 2020-03-27 07:31 UTC
[C_20200313_1543_TEST_TEST_V100000138054000.zip](https://github.com/jugglingcats/tachograph-reader/files/4392050/C_20200313_1543_TEST_TEST_V100000138054000.zip)

This is new driver file, why this file not reading your code? This is new cards file.

**Comment by jugglingcats** [comment] 2020-03-31 06:28
Duplicate of #42

**Closed by jugglingcats** 2020-03-31 06:28 UTC
