### ISSUE TITLE
Nuget error in visual studio

### ISSUE THREAD

**Issue by ramasofficial** [jugglingcats/tachograph-reader#51] opened 2019-12-05 19:55 UTC
Hello, how need to solve nuget library error?

**Comment by patientzerouk** [comment] 2019-12-05 23:54
Is this not a duplicate of issue #49 

Does the solution there not help?

**Closed** 2019-12-06 06:52 UTC

**Comment by ramasofficial** [comment] 2019-12-06 06:55
Sorry, i founded it :) Thank you so much!
